##########################################################################
# dns 설정
##########################################################################
# 설정 파일 삭제
$ rm -f /etc/resolv.conf

# 설정 파일 생성
$ sudo tee /etc/resolv.conf << EOF
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /e
tc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 172.21.32.1
nameserver 8.8.8.8
EOF

# 파일 변경 권한 설정
$ sudo chattr +i resolv.conf

##########################################################################
# wsl 설정 
##########################################################################
#! shutdown 시 초기화 되는 경우 (WSL)
#! /etc/wsl.conf 아래와 같이 설정 추가

```
[network]
generateResolvConf = false
```

$ sudo tee /etc/wsl.conf << EOF
[network]
generateResolvConf = false
EOF

$ cd /etc/resolv.conf
$ sudo chattr +i [CONFIG_FILE]


##########################################################################
# dns 고정 설정
##########################################################################
# resolvconf 설치
$ sudo apt-get update -y

$ sudo apt-get install resolvconf

$ sudo apt-get upgrade -y

# resolvconf 설치 확인
$ sudo systemctl status resolvconf.service

# 비활성 시 활성화
$ sudo systemctl start resolvconf.service
$ sudo systemctl enable resolvconf.service
$ sudo systemctl status resolvconf.service

# Default 설정 추가
$ sudo vim /etc/resolvconf/resolv.conf.d/head
```
...
nameserver 8.8.8.8
nameserver 8.8.4.4

```